dart_code_metrics:
  rules:
    - avoid-cascade-after-if-null
    - avoid-collection-methods-with-unrelated-types
    - avoid-duplicate-named-imports
    - avoid-dynamic
    - always-remove-listener
    - avoid-global-state
    - avoid-passing-async-when-sync-expected
    - avoid-redundant-async
    - avoid-self-compare
    - avoid-throw-in-catch-block
    - avoid-unnecessary-conditionals
    - avoid-unnecessary-type-assertions
    - avoid-unnecessary-type-casts
    - avoid-unrelated-type-assertions
    - avoid-unused-parameters
    - no-empty-block
    - no-equal-then-else
    - prefer-correct-test-file-name
    - prefer-iterable-of
    - prefer-match-file-name
    - avoid-unnecessary-setstate
    - avoid-unnecessary-stateful-widgets
    - check-for-equals-in-render-object-setters
    - consistent-update-render-object
    - use-setstate-synchronously
    - avoid-nested-conditional-expressions
    - avoid-non-null-assertion
    - avoid-substring
    - avoid-top-level-members-in-tests
    - binary-expression-operand-order
    - double-literal-format
    - missing-test-assertion
    - no-boolean-literal-compare
    - no-magic-number
    - prefer-async-await
    - prefer-conditional-expressions
    - prefer-enums-by-name
    - prefer-first
    - prefer-immediate-return
    - prefer-last
    - prefer-moving-to-variable
    - avoid-border-all
    - avoid-expanded-as-spacer
    - avoid-returning-widgets
    - avoid-shrink-wrap-in-lists
    - avoid-wrapping-in-padding
    - prefer-const-border-radius
    - prefer-correct-edge-insets-constructor
    - prefer-extracting-callbacks
    - prefer-text-rich
    - prefer-using-list-view
    - avoid-bloc-public-methods
    - avoid-cubits
    - avoid-duplicate-bloc-event-handlers
    - avoid-empty-build-when
    - avoid-existing-instances-in-bloc-provider
    - avoid-instantiating-in-bloc-value-provider
    - avoid-passing-bloc-to-bloc
    - avoid-passing-build-context-to-blocs
    - avoid-returning-value-from-cubit-methods
    - check-is-not-closed-after-async-gap
    - emit-new-bloc-state-instances
    - handle-bloc-event-subclasses
    - prefer-bloc-event-suffix
    - prefer-bloc-extensions
    - prefer-bloc-state-suffix
    - prefer-correct-bloc-provider
    - prefer-immutable-bloc-events
    - prefer-immutable-bloc-state
    - prefer-multi-bloc-provider
    - prefer-sealed-bloc-events
    - prefer-sealed-bloc-state
